import { GridBox, Button, ComboBox } from "std-widgets.slint";

component ColorComboBox {
    ComboBox {
        model: ["ACES (AP0)", "ARRI Wide Gamut 3", "REDWideGamutRGB", "Sony S-Gamut3.Cine"];
    }
}

component GammaComboBox {
    ComboBox {
        model: ["ARRI LogC3", "Linear", "RED Log3G10", "Sony S-Log3"];
    }
}
component ResetButton {
    Button { text: "Reset"; }    
}

export component AppWindow inherits Window {

    property <string> name;

    GridBox {
        padding: 15px;
        spacing: 15px;
        Row {
            Text { 
                text: "Input Color Space"; 
                vertical-alignment: center;
                }
            ColorComboBox{}
        }

        Row {
            Text { 
                text: "Input Gamma"; 
                vertical-alignment: center;
                }
            GammaComboBox {}
        }
        Row {
            Text { 
                text: "Output Color Space"; 
                vertical-alignment: center;
                }
            ColorComboBox{}
        }
        Row {
            Text { 
                text: "Output Gamma"; 
                vertical-alignment: center;
                }
            GammaComboBox {}
        }
        Row {
            Button {
                text: "Swap";
                col: 1;
                colspan: 1;
                primary: false;
            }
            Button {
                text: "Export";
                col: 0;
                colspan: 1;
                primary: true;
            }
        }
    }
}
